base: api.pwa-demo.ddev.site
baseVariants: {  }
errorHandling: {  }
languages:
  -
    languageId: '0'
    title: English
    navigationTitle: English
    base: /
    locale: en_US.UTF8
    iso-639-1: en
    hreflang: en-US
    direction: ltr
    typo3Language: default
    flag: us
    enabled: true
  -
    languageId: '1'
    title: Polish
    navigationTitle: Polish
    base: /pl/
    locale: pl_PL.UTF-8
    iso-639-1: pl
    hreflang: pl-PL
    direction: ltr
    typo3Language: default
    flag: pl
    fallbackType: fallback
    fallbacks: '0'
    enabled: true
  -
    languageId: '2'
    title: German
    navigationTitle: Deutsch
    base: /de/
    locale: de_DE.UTF8
    iso-639-1: de
    hreflang: de-DE
    direction: ltr
    typo3Language: de
    flag: de
    fallbackType: fallback
    fallbacks: '0'
    enabled: true
rootPageId: 1
routes: {  }
routeEnhancers:
  NewsPlugin:
    type: Extbase
    limitToPages:
      - 23
      - 24
      - 25
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
      -
        routePath: '/strona-{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
        requirements:
          page: \d+
      -
        routePath: '/arch/{year}/{month}'
        _controller: 'News::archive'
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      page:
        type: StaticRangeMapper
        start: '1'
        end: '999'
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
